# Generated by Django 4.2.3 on 2023-08-03 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField(null=True)),
                ('protein', models.IntegerField(null=True)),
                ('carbs', models.IntegerField(null=True)),
                ('fat', models.IntegerField(null=True)),
                ('fiber', models.IntegerField(null=True)),
                ('date', models.DateField(default='2023-8-3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
