# Generated by Django 4.2.3 on 2023-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddiary',
            name='carbs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fooddiary',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fooddiary',
            name='energy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fooddiary',
            name='fat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fooddiary',
            name='fiber',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fooddiary',
            name='protein',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
