# Generated by Django 4.2.3 on 2023-08-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittoapp', '0002_alter_fooddiary_carbs_alter_fooddiary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddiary',
            name='date',
            field=models.DateField(default='2023-8-4', null=True),
        ),
    ]
