# Generated by Django 4.2.3 on 2023-08-06 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fittoapp', '0004_alter_fooddiary_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBodyReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr', models.IntegerField(null=True)),
                ('daily_intake', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyreq', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
