# Generated by Django 4.2.3 on 2023-08-07 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fittoapp', '0007_fooddiary_breakfast_fooddiary_dinner_fooddiary_lunch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_done', models.CharField(max_length=50, null=True)),
                ('calories_burned', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(default='2023-8-7', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitydone', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
