# Generated by Django 4.2.3 on 2023-08-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittoapp', '0008_activitydiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydiary',
            name='date',
            field=models.DateField(default='2023-8-24', null=True),
        ),
        migrations.AlterField(
            model_name='fooddiary',
            name='date',
            field=models.DateField(default='2023-8-24', null=True),
        ),
    ]
