# Generated by Django 4.2.3 on 2023-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('G', 'Gain weight'), ('M', 'Maintain weight'), ('L', 'Lose weight')], max_length=1, null=True),
        ),
    ]
