# Generated by Django 4.2.3 on 2023-08-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('G', 'Gain weight'), ('M', 'Maintain weight'), ('L', 'Lose weight')], max_length=1, null=True, verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1, null=True, verbose_name='sex'),
        ),
    ]
