# Generated by Django 4.2.3 on 2023-08-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_goal_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('N', 'Very little or no exercise'), ('L', 'Light: exercise 1-3 times a week'), ('M', 'Moderate: exercise 4-5 times a week'), ('A', 'Active: exercise everyday or intense exercise 3-4 times a week')], max_length=1, null=True, verbose_name='activity'),
        ),
    ]
